language: java

jdk:
  - openjdk8
  
addons:
  apt:
    package:
      - openjdk-8-jre-headless
      - openjdk-8-jdk-headless

script:
  - javac src/fr/topeka/perpetualCalendar/PerpetualCalendar.java src/fr/topeka/perpetualCalendar/Algorithm.java
  - cd src/ && jar cvfe ../perpetualCalendar.jar fr.topeka.perpetualCalendar.PerpetualCalendar fr/topeka/perpetualCalendar/PerpetualCalendar.class fr/topeka/perpetualCalendar/Algorithm.class ../README.md ../LICENSE
