language: java

jdk:
  - openjdk8

script:
  - jar cf perpetualCalendar.jar src/fr/topeka/perpetualCalendar/PerpetualCalendar.java src/fr/topeka/perpetualCalendar/Algorithm.java README.md LICENSE
  - java -jar perpetualCalendar.jar
